# Site settings
name: Taka's Blog
email: gaoy4c@gmail.com
author: Gao Yuan
url: http://GawainGao.github.io
resume_site: http://GawainGao.github.io/Resume/
github: https://github.com/GawainGao/
baseurl: ""
description: Study never end!
meta_description: 
motto: 
banner: 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: GawainGao

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

